/* =============================================================================
   EarnLoop — Referral page logic (replaces ReferralPage.tsx)
   Stat cards, copyable code/link, and the invited-friends table.
   ============================================================================= */
(function () {
  "use strict";

  var seed = window.EARNLOOP_SEED;
  var refInfo = seed.referrals; // { code, link, ... }
  function $(id) { return document.getElementById(id); }

  var s = EL.store.get();
  var codeVal = refInfo.code, linkVal = refInfo.link;
  var rewardVal = s.platformSettings.referralReward;
  var listData = (s.referralList || []).slice(); // { name, joined, status, points }

  var STATUS = {
    invited: { label: "Invited", cls: "badge--secondary" },
    pending: { label: "Pending", cls: "badge--warning" },
    rewarded: { label: "Rewarded", cls: "badge--success" },
  };

  function setCount(el, val) { if (!el) return; el.setAttribute("data-count", val); animateCount(el); }

  function renderStats() {
    setCount($("ref-stat-invited"), listData.length);
    setCount($("ref-stat-joined"), listData.filter(function (r) { return r.status !== "invited"; }).length);
    setCount($("ref-stat-earned"), listData.reduce(function (sum, r) { return sum + (r.points || 0); }, 0));
    setCount($("ref-stat-reward"), rewardVal);
  }

  function renderCodeCard() {
    $("ref-code-desc").textContent =
      "Share your code or link. You'll earn " + rewardVal + " points once a friend joins and completes their first task.";
    $("ref-code").value = codeVal;
    $("ref-link").value = linkVal;
  }

  function renderList() {
    var host = $("ref-history-body");
    if (listData.length === 0) {
      host.innerHTML =
        '<div class="empty-state"><span class="empty-state__ic"><i data-lucide="users"></i></span>' +
        '<p class="empty-state__title">No invites yet</p>' +
        '<p class="empty-state__desc">Share your referral link to start earning bonus points.</p></div>';
      renderIcons();
      return;
    }
    var rows = listData.map(function (r) {
      var st = STATUS[r.status] || STATUS.pending;
      return (
        "<tr>" +
        '<td><div class="ref-friend">' +
        '<span class="avatar avatar--sm"><span class="avatar__fallback">' + EL.initials(r.name) + "</span></span>" +
        '<span class="ref-friend__name">' + EL.escapeHtml(r.name || "Friend") + "</span></div></td>" +
        '<td class="ref-joined">' + (r.joined ? EL.formatDate(r.joined) : "") + "</td>" +
        '<td><span class="badge ' + st.cls + '">' + st.label + "</span></td>" +
        '<td class="is-right ref-reward">' + (r.points > 0 ? "+" + EL.formatNumber(r.points) : "") + "</td>" +
        "</tr>"
      );
    }).join("");
    host.innerHTML =
      '<div class="table-wrap"><table class="table"><thead><tr>' +
      "<th>Friend</th><th>Joined</th><th>Status</th><th class=\"is-right\">Reward</th>" +
      "</tr></thead><tbody>" + rows + "</tbody></table></div>";
    renderIcons();
  }

  // The real code lives on the profile row (profiles.referral_code, generated by
  // supabase/referrals.sql). Older rows that predate that column fall back to
  // the same derivation the database uses, so the link still works.
  function codeFor(u) {
    if (u.referral_code) return u.referral_code;
    var base = (u.username || u.full_name || u.fullName || "user").toUpperCase().replace(/[^A-Z0-9]+/g, "-").replace(/^-+|-+$/g, "");
    var suffix = String(u.id || "").replace(/-/g, "").slice(0, 4).toUpperCase();
    return (base.slice(0, 16) || "USER") + (suffix ? "-" + suffix : "");
  }

  // Build the invite link against the folder this page is served from, so it
  // works when the app isn't at the domain root.
  function inviteLink(code) {
    var dir = location.pathname.replace(/[^/]*$/, "");
    return location.origin + dir + "auth.html?ref=" + encodeURIComponent(code);
  }

  renderStats(); renderCodeCard(); renderList();

  // Live: real code (from the profile), referral list, and reward from settings.
  (function loadLive(tries) {
    if (window.SB && window.SB.configured) {
      if (window.SB.getProfile) window.SB.getProfile().then(function (res) {
        if (res && res.data) {
          codeVal = codeFor(res.data);
          linkVal = inviteLink(codeVal);
          renderCodeCard();
        }
      });
      if (window.SB.getSettings) window.SB.getSettings().then(function (res) {
        if (res && !res.error && res.data) {
          var m = {}; res.data.forEach(function (x) { m[x.key] = x.value; });
          if (m.referral_reward != null) { rewardVal = Number(m.referral_reward) || rewardVal; renderStats(); renderCodeCard(); }
        }
      });
      if (window.SB.getReferrals) window.SB.getReferrals().then(function (res) {
        if (res && !res.error && Array.isArray(res.data)) {
          listData = res.data.map(function (r) {
            return { name: r.referred_name || "Friend", joined: r.created_at, status: r.status, points: r.reward_points || 0 };
          });
          renderStats(); renderList();
        }
      });
      return;
    }
    if ((tries || 0) < 50) setTimeout(function () { loadLive((tries || 0) + 1); }, 200);
  })(0);

  /* --- Copy buttons ----------------------------------------------------- */
  function copy(value, kind, btn) {
    var done = function () {
      btn.innerHTML = '<i data-lucide="check"></i>';
      renderIcons();
      EL.toast.success(kind === "code" ? "Referral code copied" : "Referral link copied");
      setTimeout(function () { btn.innerHTML = '<i data-lucide="copy"></i>'; renderIcons(); }, 2000);
    };
    if (navigator.clipboard && navigator.clipboard.writeText) {
      navigator.clipboard.writeText(value).then(done).catch(fallbackCopy.bind(null, value, done));
    } else {
      fallbackCopy(value, done);
    }
  }
  function fallbackCopy(value, done) {
    var ta = document.createElement("textarea");
    ta.value = value; ta.style.position = "fixed"; ta.style.opacity = "0";
    document.body.appendChild(ta); ta.select();
    try { document.execCommand("copy"); } catch (e) { /* ignore */ }
    ta.remove(); done();
  }
  $("ref-copy-code").addEventListener("click", function () { copy(codeVal, "code", this); });
  $("ref-copy-link").addEventListener("click", function () { copy(linkVal, "link", this); });

  /* --- Count-up animation ----------------------------------------------- */
  function animateCount(el) {
    var target = parseFloat(el.getAttribute("data-count")) || 0;
    var suffix = el.getAttribute("data-suffix") || "";
    var duration = 1000, start = null;
    function frame(ts) {
      if (start === null) start = ts;
      var p = Math.min((ts - start) / duration, 1);
      var eased = 1 - Math.pow(1 - p, 3);
      el.textContent = Math.round(target * eased).toLocaleString("en-US") + suffix;
      if (p < 1) requestAnimationFrame(frame);
    }
    requestAnimationFrame(frame);
  }
  function renderIcons() {
    if (window.lucide && window.lucide.createIcons) window.lucide.createIcons();
    else setTimeout(renderIcons, 60);
  }
  renderIcons();
})();
